### ISSUE TITLE
New method to get unseen inbox notification badge

### ISSUE THREAD

**Issue by Gomay88** [Telefonica/webview-bridge#162]
**Message type**: `GET_UNSEEN_NOTIFICATIONS_BADGE`

**Originator**: Web

**Min app version**: (specifies the app versions that support this method)

## Description
In order to manage the notifications inbox in [this spec](https://confluence.tid.es/display/CTO/Tech+Spec%3A+Notification+Inbox+Evolution#TechSpec) we need to get the number of unseen notifications and the timestamp to use the setUnseenInboxNotification.

The implementation have to provide the following information:

- Number of unseen notifications: The current number of unseen notifications.
- Timestamp of last update: Timestamp of the last time the notifications were updated in miliseconds

## Differences between iOS/Android (if any)

N/A

## Payload definition

**Request Payload**  
No payload required

**Response Payload**  
```ts
unseenNotificationCounter: number
lastUpdated: number
```

Examples:

```json
{"type": "GET_UNSEEN_NOTIFICATIONS_BADGE", "id": "GetUnseenNotificationsBadge", "payload": {"unseenNotificationCounter": 2, "lastUpdated": 1541415737}}
```

## Possible error cases
To be defined

**Comment by atabel** [comment]
`lastUpdated` timestamp is in seconds or miliseconds?
please define the mi app version

**Comment by Gomay88** [comment]
> `lastUpdated` timestamp is in seconds or miliseconds? please define the mi app version

As discussed in teams the time will be in miliseconds

**Comment by amegias** [comment]
Please complete the `Possible error cases` section @Gomay88. I think no errors are expected.

Regarding the default values, what happens if there is no data in the native side?? Checking your approach @Gomay88 , `lastUpdated` timestamp will be `0`, right?
Just to be aligned with @haynlo and @atabel 


https://github.com/Telefonica/iphoneapp/blob/af4d78c2194d97641f2916e4726cc53eaec8836c/Messenger/SettingsKit/Source/NotificationInbox/Repositories/NotificationInboxRepository.swift#L70

**Comment by haynlo** [comment]
@Gomay88 Keep in mind this comment from @amegias in the `SET_UNSEEN_NOTIFICATIONS_BADGE` issue: https://github.com/Telefonica/webview-bridge/issues/161#issuecomment-2442091657

Remember to update the value type also here.

**Comment by atabel** [comment]
web ticket: https://jira.tid.es/browse/WEB-2097
